apiVersion: v1
kind: Service
metadata:
  name: spring-app
spec:
  selector:
    app: spring-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30061
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  selector:
    matchLabels:
      app: spring-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: mertcakmak2/spring-mongodb-cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080